name: 'Translate: lupdate source TS in repo'

on:
  workflow_dispatch:
    inputs:
      cleanup_obsolete:
        description: "Clean up obsolete strings"
        required: true
        type: boolean
        default: false
  schedule:
    - cron: "0 12 * * Sun"

jobs:
  lupdate:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' || github.repository == 'musescore/MuseScore'
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Configure workflow
        run: |
          LUPDATE_ARGS=''
          if [[ "${{ github.event_name }}" == "schedule" || "${{ inputs.cleanup_obsolete }}" == "true" ]]; then
            LUPDATE_ARGS='-no-obsolete'
          fi

          echo "LUPDATE_ARGS=$LUPDATE_ARGS" | tee -a $GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          version: '6.8.0'
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
          archives: 'qttools'

      - name: Run lupdate
        run: |
          bash ./tools/translations/run_lupdate.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Run `lupdate` with arguments `${{ env.LUPDATE_ARGS }}`"
          branch: "ci_lupdate${{github.ref_name && format('_{0}', github.ref_name) || ''}}"
          add-paths: share/locale/*
          title: "Update in-repo translation source files"
          body: "Run `lupdate` with arguments `${{ env.LUPDATE_ARGS }}`"
          labels: strings
          reviewers: cbjeukendrup
